stages:
  Data_ingestion:
    cmd: python src/pipeline/stage_01_data_ingestion_pipeline.py
    deps: 
      - src/pipeline/stage_01_data_ingestion_pipeline.py
    outs:
      - artifacts/data_ingestion/data.csv

  Data_Transformation:
    cmd: python src/pipeline/stage_02_data_transformation_pipeline.py
    deps: 
      - src/pipeline/stage_02_data_transformation_pipeline.py
      - artifacts/data_ingestion/data.csv
    outs:
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv

  Model_Training:
    cmd: python src/pipeline/stage_03_model_trainer_pipeline.py
    deps: 
      - src/pipeline/stage_03_model_trainer_pipeline.py
      - artifacts/data_transformation/train.csv
      - params.yaml
    outs:
      - artifacts/model_trainer/model.pkl
  
  Model_evaluation:
    cmd: python src/pipeline/stage_04_model_evaluation_pipeline.py
    deps:
      - src/pipeline/stage_04_model_evaluation_pipeline.py
      - artifacts/model_trainer/model.pkl
      - artifacts/data_transformation/test.csv
    outs:
      - artifacts/model_evaluation/score.json
