xgboost:
  objective: 'reg:squarederror'
  booster: 'gbtree'              
  learning_rate: 0.3
  max_depth: 6 
  alpha: 8 
  n_estimators: 40
  gamma: 3
  verbosity: 2
  min_child_weight: 2
  reg_lambda: 1
  scale_pos_weight: 4
  eval_metric: 'rmse'