artifacts_root: artifacts

data_ingestion:
  data_ingestion_root: artifacts/data_ingestion
  data_url: 'https://drive.google.com/file/d/1brmA-6b8Q2RwRcSIemgfj_kSEIlnOEEn/view?usp=sharing'
  data_path: artifacts/data_ingestion/data.csv

