artifacts_root: artifacts

data_ingestion:
  data_ingestion_root: artifacts/data_ingestion
  data_url: 'https://drive.google.com/file/d/1brmA-6b8Q2RwRcSIemgfj_kSEIlnOEEn/view?usp=sharing'
  data_path: artifacts/data_ingestion/data.csv

data_transformation:
  data_transformation_root: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv

model_trainer:
  transformed_train_data: artifacts/data_transformation/train.csv
  model_trainer_root: artifacts/model_trainer
  model_path: artifacts/model_trainer/model.pkl
  target: cost
  

